// Firebase Configuration
// Auto-generated by Antigravity (SaaS Setup)

import { initializeApp } from "https://www.gstatic.com/firebasejs/10.7.1/firebase-app.js";
import { getFirestore } from "https://www.gstatic.com/firebasejs/10.7.1/firebase-firestore.js";
import { getAuth } from "https://www.gstatic.com/firebasejs/10.7.1/firebase-auth.js";

const firebaseConfig = {
    apiKey: "AIzaSyDcEUPMB24AM1m2j0D1fdFXU5LLtn95q4k",
    authDomain: "qr-memory-biz-app.firebaseapp.com",
    projectId: "qr-memory-biz-app",
    storageBucket: "qr-memory-biz-app.firebasestorage.app",
    messagingSenderId: "733654419351",
    appId: "1:733654419351:web:b6cdf8f61f472d688da6d2"
};

// Initialize Firebase
const app = initializeApp(firebaseConfig);
const db = getFirestore(app);
const auth = getAuth(app);

export { app, db, auth };
